stretch build

diff --git a/scripts/copy-initrd-modules b/scripts/copy-initrd-modules
--- a/scripts/copy-initrd-modules
+++ b/scripts/copy-initrd-modules
@@ -20,6 +20,7 @@ directory is included automatically.
 Options:
     --                 Read modules list on stdin
     -c --count         Display a count of the modules found
+    -C --crypt         Only copy extra modules used for encrypted live-usb
     -d --dir=DIR       Grab all modules found under DIR
     -f --from=FROM     copy from lib/modules under FROM/
     -h --help          Show this usage
@@ -36,17 +37,21 @@ Usage
 }
 
 DEFAULT_LIST="
+aes
 aufs
 battery
 block
+blowfish
 btrfs
 cdrom
 crc16
 crc32c-generic
-crct10dif-pclmul
 crct10dif-common
 crct10dif-generic
-dm_mod
+crct10dif-pclmul
+dm-crypt
+dm-mod
+ecb
 ehci-hcd
 ehci-pci
 ext2
@@ -57,9 +62,17 @@ fotg210-hcd
 fusbh200-hcd
 fuse
 hid
+hid-apple
+hid-belkin
+hid-cherry
+hid-generic
+hid-lenovo-tpkbd
+hid-logitech
 hid-logitech-dj
 hid-logitech-hidpp
-hid-generic
+hid-microsoft
+hid-monterey
+hid-samsung
 isofs
 jbd
 jbd2
@@ -68,12 +81,13 @@ libcrc32c
 loop
 mbcache
 msdos
+nls-ascii
 nls-cp437
 nls-utf8
 ntfs
 nvme
-ohci-pci
 ohci-hcd
+ohci-pci
 overlay
 pcie-aspm
 printk
@@ -82,7 +96,9 @@ reiserfs
 rts5139
 scsi-mod
 sd-mod
+serpent
 sg
+sha256
 shpchp
 squashfs
 sr-mod
@@ -105,6 +121,14 @@ xhci-hcd
 xhci-pci
 "
 
+CRYPT_LIST="
+dm-crypt
+dm-mod
+serpent
+sha256
+blowfish
+aes
+"
 # i915
 # nouveau
 # radeon
@@ -141,11 +165,12 @@ main() {
         case $arg in
                   -) USE_STDIN=true                  ;;
            -count|c) SHOW_COUNT=true                 ;;
+           -crypt|C) DO_CRYPT=true                   ;;
              -dir|d) DIRS="$DIRS,$val"               ;;
             -help|h) usage                           ;;
-            -from|f) from_dir=$val                   ;;
+            -from|f) from_dir=${val%/}               ;;
           -kernel|k) kernel=$val                     ;;
-              -to|t) to_dir=$val                     ;;
+              -to|t) to_dir=${val%/}                 ;;
          -pretend|p) PRETEND=true                    ;;
            -quiet|q) QUIET=true                      ;;
       -very-quiet|Q) VERY_QUIET=true                 ;;
@@ -158,37 +183,39 @@ main() {
     [ "$QUIET" -o "$VERY_QUIET" ] && MP_ARGS="$MP_ARGS --quiet"
     # fill in default kernel if there is only one
     if [ -z "$kernel" ]; then
-        local d=$from_dir/lib/modules
-        test -d $d || fatal "Could not find directory $d"
-        [ "$(ls $d | wc -l)" = 1 ] && kernel=$(ls $d)
+        local d="$from_dir/lib/modules"
+        test -d "$d" || fatal "Could not find directory \"$d\""
+        [ "$(ls "$d" | wc -l)" = 1 ] && kernel=$(ls "$d")
     fi
 
     [ "$kernel"   ] && MP_ARGS="$MP_ARGS -S $kernel"
-    [ "$from_dir" ] && MP_ARGS="$MP_ARGS -d $from_dir"
+    [ "$from_dir" ] && MP_ARGS="$MP_ARGS -d \"$from_dir\""
 
     : ${kernel:=$(uname -r)}
     : ${to_dir:=.}
 
-    local mod_dir=$from_dir/lib/modules/$kernel
+    local mod_dir="$from_dir/lib/modules/$kernel"
     test -d "$mod_dir" || fatal "Directory $mod_dir does not exist"
 
     local list1 list2 repeats default_mode
     # grab list from files or stdin and strip comments
 
+    [ "$DO_CRYPT" ] && DEFAULT_LIST=$CRYPT_LIST
+
     if [ -z "$USE_STDIN" -a $# -eq 0 ]; then
         default_mode=true
         list1=$(echo "$DEFAULT_LIST" | grep -v "^\s*#" | sed 's/\s*#.*//')
     else
-        list1=$(cat "$@" | grep -v "^\s*#" | sed 's/\s*#.*//')
+        list1=$(cat "$@" | grep -v "^\s*#" | sed -e 's/\s*#.*//' -e "s/,/ /g")
     fi
 
     [ "$default_mode" -a -z "$DIRS" ] && DIRS="kernel/drivers/ata kernel/drivers/mmc"
     local d
     for d in $(echo $DIRS | sed 's/,/ /g'); do
         local dir=$mod_dir/$d
-        test -d $dir || fatal "Subdirectory $dir does not exist"
+        test -d "$dir" || fatal "Subdirectory $dir does not exist"
         list1="$list1
-$(find $dir -name "*.ko" -printf "%f\n" | sed 's/\.ko//')"
+$(find "$dir" -name "*.ko" -printf "%f\n" | sed 's/\.ko//')"
     done
 
     repeats=$(echo "$list1" | sed 's/_/-/g' | sort | uniq --repeated | grep .)
@@ -198,20 +225,25 @@ $(find $dir -name "*.ko" -printf "%f\n" | sed 's/\.ko//')"
         echo "$repeats" >&2
     fi
 
-
     list2=$(echo "$list1" | sed 's/_/-/g' | sort -u \
-        | xargs modprobe $MP_ARGS | sed -n 's/^insmod //p' | sort -u)
+        | eval "xargs modprobe $MP_ARGS" | sed -n 's/^insmod //p' | sort -u)
 
     local full cnt=0
-    for full in $list2; do
-        [ "$VERBOSE" ] && printf "  %s\n" $(basename $full)
-        local dir=$(dirname $full)
-        dir=$to_dir/${dir##$from_dir/}
-        test -d $dir || echo_cmd mkdir -p $dir
-        echo_cmd cp $full $dir/
+    [ -z "${from_dir##/*}" ] || from_dir="$PWD/$from_dir"
+    while read full; do
+        [ "$VERBOSE" ] && printf "  %s\n" "$(basename "$full")"
+        local dir=$(dirname "$full")
+        dir="$to_dir/${dir##$from_dir/}"
+        test -d "$dir" || echo_cmd mkdir -p "$dir"
+        echo_cmd cp "$full" "$dir/"
         cnt=$((++cnt))
-    done
-    [ "$SHOW_COUNT" ] && echo "$ME: $cnt module(s)"
+    done<<List_2
+$(echo "$list2")
+List_2
+
+    [ "$SHOW_COUNT" ] && printf "$ME: %s module(s)\n" "$cnt"
+
+    exit 0
 }
 
 echo_cmd() {
